---
- name: Scan le reseau local, et ajoute a Zabbix
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /home/edouard/myenv/bin/python3
  tasks:
    - name: Nmap scan le reseau local
      command: "nmap -sn 192.168.1.0/24"
      register: nmap_output

    - name: Extraction des IPs et des noms
      set_fact:
        nmap_hosts: "{{ nmap_output.stdout_lines | select('match', 'Nmap scan report') | list }}"

    - name: Filtre des IPs et des noms
      set_fact:
        clean_hosts: "{{ nmap_hosts | map('regex_replace', 'Nmap scan report for ([\\S]+) \\(([^\\)]+)\\)', '\\1 \\2') | map('regex_replace', 'Nmap scan report for ([\\d.]+)', '\\1') | list }}"

    - name: Recuperation uniquement des IPs et des noms
      set_fact:
        filtered_hosts: "{{ clean_hosts | select('search', '[a-zA-Z]') | list }}"

    - name: Separation des IPs et des noms
      set_fact:
        host_ip_pairs: "{{ filtered_hosts | map('split', ' ') | list }}"

    - name: Insertion des machines decouvertes dans zabbix
      include_tasks: insert_hosts.yml
      loop: "{{ host_ip_pairs }}"
      loop_control:
        loop_var: item


